# Generated by Django 4.1.3 on 2023-02-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_follow_followers_alter_follow_following_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='liked',
            field=models.BooleanField(default=False),
        ),
    ]
