# Generated by Django 4.1.3 on 2023-02-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_remove_posts_liked_posts_likeduser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='numberLikes',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
